### ISSUE TITLE
+astでコンパイルしたjson.nzcをload時segmentation faultが発生する

### ISSUE THREAD

**Issue by Kouhei-Moriya** [imasahiro/moz#23]
nez-1/oldsample/json.nezを--option:+ast:-memoでコンパイル時、
src/loader.c:661においてSegmentation faultが発生する

**Comment by imasahiro** [comment]
I cannot reproduce in my environment(OSX 10.10, clang 3.6.2, nez e35b21493).
Please tell me about your environment.
