### ISSUE TITLE
TblJumpおよびその直後のJump先がNonterminal外のFailになる

### ISSUE THREAD

**Issue by Kouhei-Moriya** [imasahiro/moz#24]
$ sample.nez
File = { NONTERMINAL }
NONTERMINAL = 'a' TEXT1 / [b-c] TEXT2
TEXT1 = 'd' / [e-f]+
TEXT2 = 'g' 'h'? / 'i' 
$ java -jar nez.jar compile --option:-ast:-inline -p sample.nez
$ cat input.txt
aef
$ moz -p sample.nzc -i input.txt
nterm0 File
nterm1 NONTERMINAL
nterm2 TEXT1
nterm3 TEXT2
set: [b-c]
set: [e-f]
Nterm0 File
56021316, 0000, Call 1 0 5 
56021327, 0001, Ret 
Nterm1 NONTERMINAL
56021332, 0002, TblJump2 
56021335, 0003, Fail 
56021336, 0004, Byte 97 'a' 
56021338, 0005, Call 2 0 19
56021349, 0006, Ret 
56021354, 0007, Set 0x3584a60 [b-c]
56021357, 0008, Call 3 -19 26
Nterm2 TEXT1
56021368, 0009, TblJump2 
56021371, 0010, Jump -41 
56021376, 0011, Byte 100 'd' 
56021378, 0012, Ret 
56021383, 0013, Set 0x3584a80 [e-f]
56021386, 0014, RSet 0x3584a80 [e-f]
56021389, 0015, Ret 
Nterm3 TEXT2
56021394, 0016, TblJump2 
56021397, 0017, Jump -67 
56021402, 0018, Byte 103 'g' 
56021404, 0019, OByte 104 'h' 
56021406, 0020, Ret 
56021411, 0021, Byte 105 'i' 
56021413, 0022, Ret 
この例の場合、TEXT1およびTEXT2におけるTblJump2のdefaultの飛び先、
およびその直後のJumpの飛び先がNONTERMINALのFailを指している。

**Comment by imasahiro** [comment]
It's not a bug, it's a feature.
